kind = "web"
previewPath = "/"
title = "EBON Panel"
version = "1.0.0"
id = "artifacts/ebon-panel"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 18384

[services.development]
run = "pnpm --filter @workspace/ebon-panel run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/ebon-panel", "run", "build" ]
publicDir = "artifacts/ebon-panel/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "18384"
BASE_PATH = "/"
